### ISSUE TITLE
Unexpected scrolling behavior while mouse-selecting a subset of sample code

### ISSUE THREAD

**Issue by galeyang** [flutter/website#1756]
From recent UX studies, 3 out of 4 participants had a usability issue: on the Flutter.io, when selecting sample code that was close to the top of the browser, participants unexpectedly selected text in the sidebar.

![selectbug](https://user-images.githubusercontent.com/5102864/48812063-6d498200-ece5-11e8-8ffa-626f4a2d26c8.gif)

The expected behavior shown in the below gif: it should scroll up as the cursor move up.
![selectcard](https://user-images.githubusercontent.com/5102864/48812067-6f134580-ece5-11e8-89ff-8329b6a34536.gif)

cc: @jayoung-lee @InMatrix

**Comment by chalin** [comment]
Maybe we should just add a copy-code button (like we have on [webdev](https://webdev.dartlang.org) and [developers](https://developers.google.com/). For example:

- https://developers.google.com/web/fundamentals/design-and-ux/input/forms/#the_importance_of_labels
  > <img width="470" alt="screen shot 2018-11-21 at 15 37 59" src="https://user-images.githubusercontent.com/4140793/48867272-aba57680-eda3-11e8-9a8f-b8c71bfbe40c.png">

- https://webdev.dartlang.org/angular/tutorial/toh-pt0#angular-app-basics, iif you hover over the code you'll see a COPY CODE button appear:
  > <img width="589" alt="screen shot 2018-11-21 at 15 36 09" src="https://user-images.githubusercontent.com/4140793/48867222-80bb2280-eda3-11e8-81a2-a074cde06977.png">

Thoughts?

**Comment by fertolg** [comment]
If we already have this on webdev, I would vote to bring this into our shared components so we can use it across different sites. I'll also look into how to limit the text selection to just that box, I believe what's happening is that because the nav is fixed, the cursor is suddenly above the nav which makes the browser select every text node in the dom up to the nav (the whole site).

**Comment by galeyang** [comment]
+1 to this copy-code button! In the same study, I did get some feedback about missing this copy-all button.

@fertolg Thanks for looking into this issue! When I first noticed this partial selection problem, I also believed this was the default browser behavior when our website has a fixed top nav. Later on, I found the [Card API doc ](https://docs.flutter.io/flutter/material/Card-class.html) didn't have this issue. I'm not sure if the HTML structure has any impact on it.

**Comment by galeyang** [comment]
The problem of selecting a subset of code still exists so I reopen the issue. This is not urgent.

**Comment by chalin** [comment]
Ok, thanks. I'll adjust the priority.

**Comment by MiraMarshall** [comment]
Closed. The issue is fixed. There is a copy code button and users can select a subset of code. 

https://user-images.githubusercontent.com/23406866/172899272-30192b90-e8b3-4cc9-97ef-15072e9d7931.mov
